name: Run

on: 
  push:
  schedule:
  - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: webdriver
      run: |
        cd ~
        wget http://mirrors.kernel.org/ubuntu/pool/universe/c/chromium-browser/chromium-browser_80.0.3987.163-0ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/c/chromium-browser/chromium-chromedriver_80.0.3987.163-0ubuntu1_amd64.deb
        sudo dpkg -i chromium-browser_80.0.3987.163-0ubuntu1_amd64.deb chromium-chromedriver_80.0.3987.163-0ubuntu1_amd64.deb 
        chromedriver --version
        google-chrome --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install opencv-python
        pip install selenium
        pip install Pillow
    - name: run
      run: python text.py
