name: Run

on: 
  push:
  schedule:
  - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: webdriver
      run: sudo apt install chromium-chromedriver
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install opencv-python
        pip install selenium
        pip install Pillow
    - name: run
      run: python text.py
